apiVersion: v1
kind: Service
metadata:
  name: dspaces-api-service
  labels:
    app: dspaces-api
  namespace: dspaces
spec:
  selector:
    app: dspaces-api
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  type: ClusterIP  
