apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose-resolved.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dspaces
  name: dspaces
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: dspaces
