apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: scidx-kafka-controllers
  namespace: kafka
  labels:
    strimzi.io/cluster: scidx-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: scidx-kafka-brokers
  namespace: kafka
  labels:
    strimzi.io/cluster: scidx-kafka
spec:
  replicas: 4
  roles:
    - broker
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: scidx-kafka
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV0
    listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # TODO: add logic to assign different advertisedHost per broker
          brokers:
            - broker: 0
              advertisedHost: 
              nodePort: 31090
            - broker: 1
              advertisedHost: 
              nodePort: 31091
            - broker: 2
              advertisedHost: 
              nodePort: 31092
            - broker: 3
              advertisedHost: 
              nodePort: 31093
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  # entityOperator:
  #   topicOperator: {}
  #   userOperator: {}


