# This YAML file defines a Kafka cluster with:

# 1. 3 Kafka brokers and 3 Zookeeper nodes.
# 2. Persistent storage for both Kafka (10Gi per broker) and Zookeeper (5Gi per node).
# 3. Internal-only access to Kafka on port 9092 without TLS.
# 4. Replication factors and minimum in-sync replicas are configured for fault tolerance

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: scidx-kafka-cluster
spec:
  # Kafka cluster configuration
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      default.replication.factor: 3
      min.insync.replicas: 2
  # Zookeeper configuration
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      