apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-api
  namespace: pop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pop-api
  template:
    metadata:
      labels:
        app: pop-api
    spec:
      containers:
      - name: pop-api
        image: yutianqin/pop-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: pop-env-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
