apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
  namespace: kafka
spec:
  kafka:
    version: 3.8.1
    replicas: 4
    listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: a4833e78600424b888132ece5a38d586-244848997.us-west-2.elb.amazonaws.com
              nodePort: 31090
            - broker: 1
              advertisedHost: a4833e78600424b888132ece5a38d586-244848997.us-west-2.elb.amazonaws.com
              nodePort: 31091
            - broker: 2
              advertisedHost: a4833e78600424b888132ece5a38d586-244848997.us-west-2.elb.amazonaws.com
              nodePort: 31092
            - broker: 3
              advertisedHost: a4833e78600424b888132ece5a38d586-244848997.us-west-2.elb.amazonaws.com
              nodePort: 31093
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}