apiVersion: v1
kind: Secret
metadata:
  name: pop-env-secret
  namespace: pop
type: Opaque
stringData:
  ROOT_PATH: '/api'
  # ==============================================
  # CKAN Configuration
  # ==============================================
  CKAN_LOCAL_ENABLED: ""  # Enable or disable the local CKAN instance (True/False)
  CKAN_URL: ""            # Base URL of your local CKAN instance
  CKAN_API_KEY: ""        # API Key for CKAN authentication
  CKAN_GLOBAL_URL: ""     # Global URL for CKAN instance (Public URL)

  # ==============================================
  # Pre-CKAN Configuration (Optional)
  # ==============================================
  PRE_CKAN_ENABLED: ""    # Enable or disable the Pre-CKAN instance (True/False)
  PRE_CKAN_URL: ""        # URL of the Pre-CKAN instance
  PRE_CKAN_API_KEY: ""    # API key for Pre-CKAN authentication

  # ==============================================
  # Streaming Configuration
  # ==============================================
  KAFKA_CONNECTION: ""    # Enable or disable Kafka connectivity (True/False)
  KAFKA_HOST: ""          # Kafka broker hostname or IP address
  KAFKA_PORT: ""          # Kafka broker port number

  # ==============================================
  # Keycloak Authentication Configuration
  # ==============================================
  KEYCLOAK_URL: ""        # URL of your Keycloak authentication server
  REALM_NAME: ""          # Realm name configured in Keycloak for user management
  CLIENT_ID: ""           # Client ID registered in Keycloak realm
  CLIENT_SECRET: ""       # Client secret for authenticating the API client

  # ==============================================
  # Test User Credentials (for local testing only)
  # ==============================================
  TEST_USERNAME: ""       # Leave blank in production
  TEST_PASSWORD: ""       # Leave blank in production

  # ==============================================
  # Swagger Documentation Settings
  # ==============================================
  SWAGGER_TITLE: ""       # Title displayed in Swagger UI
  SWAGGER_DESCRIPTION: "" # Description displayed in Swagger UI

  # ==============================================
  # External Service Integrations
  # ==============================================
  USE_JUPYTERLAB: ""      # Enable or disable JupyterLab integration (True/False)
  JUPYTER_URL: ""         # URL to your JupyterLab instance
  USE_DXSPACES: ""        # Enable or disable DXSpaces integration (True/False)
  DXSPACES_URL: ""        # URL to your DXSpaces instance