apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
  namespace: kafka
spec:
  kafka:
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          externalTrafficPolicy: Local
          bootstrap:
            loadBalancerIP: ad19ae7af243c463a94860e8ff70e312-1196399255.us-west-2.elb.amazonaws.com # Optional: Specify if you have a static IP
            annotations: {}
          brokers:
            - broker: 0
              nodePort: 31090
              # advertisedHost: 44.235.27.107
              # advertisedPort: 31090
            - broker: 1
              nodePort: 31091
              # advertisedHost: 44.235.27.107
              # advertisedPort: 31091
            - broker: 2
              nodePort: 31092
              # advertisedHost: 44.235.27.107
              # advertisedPort: 31092
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}